Traceback (most recent call last):
  File "./function/nGrammeFinder.py", line 65, in <module>
    __precision(int(sys.argv[1]))
  File "./function/nGrammeFinder.py", line 52, in __precision
    res = diagnostic_langue_str(text_finder(path),N)
  File "./function/nGrammeFinder.py", line 41, in diagnostic_langue_str
    return verify_sorted[0][1]
IndexError: list index out of range